image: docker:latest

services:
- docker:dind

discord:
  stage: accessories
  script:
  - docker build --pull -t "$CI_REGISTRY_IMAGE/discord:latest" discord
  - docker push "$CI_REGISTRY_IMAGE/discord:latest"

overviewer:
  stage: accessories
  script:
  - docker build --pull -t "$CI_REGISTRY_IMAGE/overviewer:1.12" overviewer --build-arg "VERSION=1.12.2"
  - docker push "$CI_REGISTRY_IMAGE/overviewer:1.12"

server_1_12:
  stage: server
  script:
  - docker build --pull -t "$CI_REGISTRY_IMAGE/server:1.12" server --build-arg "JAR=https://launcher.mojang.com/v1/objects/886945bfb2b978778c3a0288fd7fab09d315b25f/server.jar"
  - docker push "$CI_REGISTRY_IMAGE/server:1.12"

server_1_13:
  stage: server
  script:
  - docker build --pull -t "$CI_REGISTRY_IMAGE/server:1.13" server --build-arg "JAR=https://launcher.mojang.com/v1/objects/3737db93722a9e39eeada7c27e7aca28b144ffa7/server.jar"
  - docker push "$CI_REGISTRY_IMAGE/server:1.13"

server_1_14:
  stage: server
  script:
  - docker build --pull -t "$CI_REGISTRY_IMAGE/server:1.14" server --build-arg "JAR=https://launcher.mojang.com/v1/objects/808be3869e2ca6b62378f9f4b33c946621620019/server.jar"
  - docker push "$CI_REGISTRY_IMAGE/server:1.14"

before_script:
- docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

stages:
- accessories
- server