version: '3'

services:

  backup:
    image: alexanderczigler/minecraft-backup
    environment:
      MINECRAFT_SERVER: server
      MINERACFT_SERVER_PORT: 25575
      MINECRAFT_RCON_PASSWORD: my-rcon-password
    volumes:
      - backup:/backup
      - minecraft:/mc

  discord:
    image: alexanderczigler/minecraft-discord
    environment:
      # Set your Discord webhook here.
      - WEBHOOK=<paste your webhook here>
    volumes:
      - minecraft:/mc:nocopy

  nginx:
    image: nginx
    networks:
      - default
    volumes:
      - map:/usr/share/nginx/html:ro,nocopy
    ports:
      - 80:80

  overviewer:
    image: alexanderczigler/minecraft-overviewer
    volumes:
      - map:/home/overviewer/map
      - minecraft:/mc:nocopy

  server:
    image: alexanderczigler/minecraft-server
    environment:
      - MEMORY_LIMIT=2
      - RCON_ENABLE=true
      - RCON_PASSWORD=my-rcon-password
    ports:
      - "25565:25565" # server
      - "25575:25575" # rcon
    volumes:
      - minecraft:/mc

volumes:
  backup:
  map:
  minecraft:
