version: '3.8'

services:

  # Minecraft server
  server:
    image: iteamacr/minecraft-server:1.17
    networks:
      - default
    ports:
      - "25565:25565" # server
      - "25575:25575" # rcon
    volumes:
      - minecraft:/mc

volumes:
  minecraft: