name: Build & publish packages

on:
  schedule:
  - cron:  '0 3 * * 2'
  push:
    branches: 
      - master

jobs:

  backup:
    name: Minecraft backup image
    needs: server
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
        run: echo $DOCKER_TOKEN | docker login --username "$DOCKER_USER" --password-stdin

      - name: Build image
        run: docker build --pull -t iteamacr/minecraft-backup backup

      - name: Push image to Docker Hub
        run: docker push iteamacr/minecraft-backup

  discord:
    name: Minecraft discord image
    needs: server
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
        run: echo $DOCKER_TOKEN | docker login --username "$DOCKER_USER" --password-stdin

      - name: Build image
        run: docker build --pull -t iteamacr/minecraft-discord discord

      - name: Push image to Docker Hub
        run: docker push iteamacr/minecraft-discord

  overviewer:
    name: Minecraft overviewer image
    needs: server
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
        run: echo $DOCKER_TOKEN | docker login --username "$DOCKER_USER" --password-stdin

      - name: Build image
        run: docker build --pull --build-arg minecraft_version=1.17 -t iteamacr/minecraft-overviewer:1.17 overviewer

      - name: Push image to Docker Hub
        run: docker push iteamacr/minecraft-overviewer:1.17

  server:
    name: Minecraft server image
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
        run: echo $DOCKER_TOKEN | docker login --username "$DOCKER_USER" --password-stdin

      - name: Build image
        run: docker build --pull -t iteamacr/minecraft-server:1.17 server --build-arg "JAR=https://launcher.mojang.com/v1/objects/a16d67e5807f57fc4e550299cf20226194497dc2/server.jar"

      - name: Push image to Docker Hub
        run: docker push iteamacr/minecraft-server:1.17
