name: Release

on:
  push:
    branches:
    - main
  schedule:
    - cron: "0 4 1,15 * *"

jobs:

  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        context: [backup, discord, overviewer, server]

    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v3

      - name: 💾 Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: 🐳 Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: 🔐 Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: alexanderczigler
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: 🔧 Build and push to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.context }}
          platforms: "linux/amd64,linux/arm64"
          push: true
          tags: alexanderczigler/minecraft-${{ matrix.context }}:latest,alexanderczigler/minecraft-${{ matrix.context }}:1.19.3
